[package]
name = "rust_paisy2pdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minijinja = "1.0.20"
regex = "*"
lazy_static = "*"

[profile.release]
lto = true
codegen-units = 1